_target_: transformers.AutoTokenizer.from_pretrained
pretrained_model_name_or_path: ${args.model_args.model_name_or_path}
cache_dir: ${args.model_args.cache_dir}
use_fast: ${args.model_args.use_fast_tokenizer}
revision: ${args.model_args.model_revision}
token: ${args.model_args.token}
trust_remote_code: ${args.model_args.trust_remote_code}
